name: CI - Run Tests and Publish Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.100"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Install Allure CLI
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - run: npm install -g allure-commandline --save-dev

      - name: Run Tests with Allure Results
        run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory "allure-results"

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Deploy only on main pushes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        uses: actions/setup-java@v4
        with:
          java-version: "17"
      - run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
